[package]
name = "ui-sample"
version = "0.1.0"
authors = ["Quan Pham <doraemonfanclub@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qt_widgets = "0.5"
